apiVersion: v1
kind: ConfigMap
metadata:
  name: ostad-config
  namespace: aninda-sarker-rahul-ns
data:
  MONGO_ROOT_USERNAME: "admin"
  MONGO_ROOT_PASSWORD: "password"
  MONGO_DATABASE: "ostaddb"
  MONGO_URI: "mongodb://admin:password@mongo:27017/ostaddb?authSource=admin"
---
apiVersion: v1
kind: Secret
metadata:
  name: ostad-secrets
  namespace: aninda-sarker-rahul-ns
type: Opaque
data:
  # Base64 encoded values
  # admin = YWRtaW4=
  # password = cGFzc3dvcmQ=
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: cGFzc3dvcmQ=
