replicaCount: 1

image:
  repository: mongo
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 27017

auth:
  rootUsername: ostad
  rootPassword: ostad

persistence:
  enabled: false

resources: {}

nodeSelector: {}
tolerations: []
affinity: {}

autoscaling:
  enabled: false

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}
securityContext: {}

ingress:
  enabled: false
